%QUARTUS_ROOTDIR%\\bin\\quartus_pgm.exe -m jtag -c USB-Blaster[USB-0] -o "p;DE1_D5M.sof"
@ set SOPC_BUILDER_PATH_71=%SOPC_KIT_NIOS2%+%SOPC_BUILDER_PATH_71%
@ set SOPC_BUILDER_PATH_72=%SOPC_KIT_NIOS2%+%SOPC_BUILDER_PATH_72%
@ set SOPC_BUILDER_PATH_80=%SOPC_KIT_NIOS2%+%SOPC_BUILDER_PATH_80%
@ set SOPC_BUILDER_PATH_81=%SOPC_KIT_NIOS2%+%SOPC_BUILDER_PATH_81%
@ set SOPC_BUILDER_PATH_90=%SOPC_KIT_NIOS2%+%SOPC_BUILDER_PATH_90%
@ set SOPC_BUILDER_PATH_91=%SOPC_KIT_NIOS2%+%SOPC_BUILDER_PATH_91%
@ set SOPC_BUILDER_PATH_92=%SOPC_KIT_NIOS2%+%SOPC_BUILDER_PATH_92%
@ set SOPC_BUILDER_PATH_100=%SOPC_KIT_NIOS2%+%SOPC_BUILDER_PATH_100%
@ set SOPC_BUILDER_PATH_101=%SOPC_KIT_NIOS2%+%SOPC_BUILDER_PATH_101%
@ set SOPC_BUILDER_PATH_102=%SOPC_KIT_NIOS2%+%SOPC_BUILDER_PATH_102%
@ set SOPC_BUILDER_PATH_110=%SOPC_KIT_NIOS2%+%SOPC_BUILDER_PATH_110%
@ set SOPC_BUILDER_PATH_111=%SOPC_KIT_NIOS2%+%SOPC_BUILDER_PATH_111%
@ set SOPC_BUILDER_PATH_112=%SOPC_KIT_NIOS2%+%SOPC_BUILDER_PATH_112%
@ set SOPC_BUILDER_PATH_120=%SOPC_KIT_NIOS2%+%SOPC_BUILDER_PATH_120%
@ set SOPC_BUILDER_PATH_121=%SOPC_KIT_NIOS2%+%SOPC_BUILDER_PATH_121%
@ set SOPC_BUILDER_PATH_122=%SOPC_KIT_NIOS2%+%SOPC_BUILDER_PATH_122%